export type TPropertyListing = {
  id: number;
  address: string;
  bedrooms: string;
  bathrooms: string;
  price: string;
  yearBuilt: string;
  listingDataSource: string;
  longitude: string;
  latitude: string;
  livingArea: string;
  lotSize: string;
  currency: string;
  dateSoldString: string;
  country: string;
  livingAreaUnits: string;
  description: string;
  daysOnZillow: string;
  brokerageName: string;
  propertyTypeDimension: string;
  photos: string;
  url: string | null;
  isFeatured: string;
  interior: string;
  tag: string | null;
  lastSoldPrice: string;
  priceHistory: string;
  createdAt: Date;
  updatedAt: Date;
};

export type TUser = {
  id: number;
  email: string;
  password: string;
  name: string | null;
  isAdmin: boolean;
  createdAt: Date;
  updatedAt: Date;
};
